"""add_clients_products_eav_pricing_egais

Revision ID: 44596e638f79
Revises: d8cd9a6114ef
Create Date: 2026-06-07 09:45:11.059384

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44596e638f79"
down_revision: str | Sequence[str] | None = "d8cd9a6114ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alcohol_licenses",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("license_number", sa.String(length=100), nullable=False),
        sa.Column("license_type", sa.String(length=50), nullable=False),
        sa.Column("issued_date", sa.String(length=10), nullable=False),
        sa.Column("expiry_date", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alcohol_licenses_org_id"), "alcohol_licenses", ["org_id"], unique=False
    )
    op.create_table(
        "clients",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("birth_date", sa.String(length=10), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("loyalty_points", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clients_org_id"), "clients", ["org_id"], unique=False)
    op.create_table(
        "discount_rules",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("discount_type", sa.String(length=20), nullable=False),
        sa.Column("value", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("min_purchase", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_active", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discount_rules_org_id"), "discount_rules", ["org_id"], unique=False
    )
    op.create_table(
        "entity_types",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entity_types_org_id"), "entity_types", ["org_id"], unique=False
    )
    op.create_table(
        "product_categories",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_categories_org_id"),
        "product_categories",
        ["org_id"],
        unique=False,
    )
    op.create_table(
        "tax_rates",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("is_default", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tax_rates_org_id"), "tax_rates", ["org_id"], unique=False)
    op.create_table(
        "eav_attributes",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("entity_type_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("field_type", sa.String(length=50), nullable=False),
        sa.Column("is_required", sa.Integer(), nullable=False),
        sa.Column("default_value", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entity_type_id"], ["entity_types.id"]),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eav_attributes_entity_type_id"),
        "eav_attributes",
        ["entity_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eav_attributes_org_id"), "eav_attributes", ["org_id"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("barcode", sa.String(length=100), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["category_id"], ["product_categories.id"]),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_products_category_id"), "products", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_products_org_id"), "products", ["org_id"], unique=False)
    op.create_table(
        "alcohol_products",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("egais_code", sa.String(length=255), nullable=False),
        sa.Column("alcohol_percent", sa.String(length=10), nullable=False),
        sa.Column("volume", sa.String(length=50), nullable=False),
        sa.Column("license_number", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alcohol_products_org_id"), "alcohol_products", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_alcohol_products_product_id"),
        "alcohol_products",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "eav_values",
        sa.Column("attribute_id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["attribute_id"], ["eav_attributes.id"]),
        sa.PrimaryKeyConstraint("attribute_id", "entity_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("eav_values")
    op.drop_index(op.f("ix_alcohol_products_product_id"), table_name="alcohol_products")
    op.drop_index(op.f("ix_alcohol_products_org_id"), table_name="alcohol_products")
    op.drop_table("alcohol_products")
    op.drop_index(op.f("ix_products_org_id"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_eav_attributes_org_id"), table_name="eav_attributes")
    op.drop_index(op.f("ix_eav_attributes_entity_type_id"), table_name="eav_attributes")
    op.drop_table("eav_attributes")
    op.drop_index(op.f("ix_tax_rates_org_id"), table_name="tax_rates")
    op.drop_table("tax_rates")
    op.drop_index(op.f("ix_product_categories_org_id"), table_name="product_categories")
    op.drop_table("product_categories")
    op.drop_index(op.f("ix_entity_types_org_id"), table_name="entity_types")
    op.drop_table("entity_types")
    op.drop_index(op.f("ix_discount_rules_org_id"), table_name="discount_rules")
    op.drop_table("discount_rules")
    op.drop_index(op.f("ix_clients_org_id"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(op.f("ix_alcohol_licenses_org_id"), table_name="alcohol_licenses")
    op.drop_table("alcohol_licenses")
    # ### end Alembic commands ###
