"""widen execution_date to include time

Revision ID: d0fca6999fa9
Revises: ea5a6e460e8d
Create Date: 2026-06-07 16:58:22.949359

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0fca6999fa9"
down_revision: str | Sequence[str] | None = "ea5a6e460e8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "execution_date",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=16),
        existing_nullable=False,
        existing_server_default=sa.text("''::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "execution_date",
        existing_type=sa.String(length=16),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
        existing_server_default=sa.text("''::character varying"),
    )
    # ### end Alembic commands ###
